openapi: 3.0.0
info:
  title: Service Reservas App Kotlin
  description: Service Reservas App Kotlin
  termsOfService: https://sample.com/terms/
  contact:
    name: API Support
    url: https://www.sample.com/support
    email: support@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: http://localhost:5000/service--reservas-app-kotlin
  - url: https://apps-dev.grupo.com.br/sample
  - url: http://localhost:9090/service--reservas-app-kotlin
